/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AudioWaveSVG: typeof import('./components/ComplexIcons/AudioWaveSVG.vue')['default']
    CircularIconSVG: typeof import('./components/ComplexIcons/CircularIconSVG.vue')['default']
    ContactSection: typeof import('./components/Sections/ContactSection.vue')['default']
    ExperienceSection: typeof import('./components/Sections/ExperienceSection.vue')['default']
    Header: typeof import('./components/Header.vue')['default']
    InterestCard: typeof import('./components/Cards/InterestCard.vue')['default']
    InterestsSection: typeof import('./components/Sections/InterestsSection.vue')['default']
    MainSection: typeof import('./components/Sections/MainSection.vue')['default']
    MicrophoneSVG: typeof import('./components/ComplexIcons/MicrophoneSVG.vue')['default']
    ProjectCard: typeof import('./components/Cards/ProjectCard.vue')['default']
    ProjectDetailVue: typeof import('./components/Projects/ProjectDetailVue.vue')['default']
    ProjectsSection: typeof import('./components/Sections/ProjectsSection.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SkillCard: typeof import('./components/Cards/SkillCard.vue')['default']
    SkillsSection: typeof import('./components/Sections/SkillsSection.vue')['default']
    TheFooter: typeof import('./components/TheFooter.vue')['default']
    TheInput: typeof import('./components/TheInput.vue')['default']
    TimelineItem: typeof import('./components/TimelineItem.vue')['default']
  }
}
